news_website/models/__init__.py
__author__ = 'willmcginnis'

news_website/forms/__init__.py
__author__ = 'willmcginnis'

news_website/forms/public.py
# -*- coding: utf-8 -*-
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired

from news_website.models.user import User


class LoginForm(Form):
    username = TextField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        initial_validation = super(LoginForm, self).validate()
        if not initial_validation:
            return False

        self.user = User.query.filter_by(username=self.username.data).first()
        if not self.user:
            self.username.errors.append('Unknown username')
            return False

        if not self.user.check_password(self.password.data):
            self.password.errors.append('Invalid password')
            return False

        if not self.user.active:
            self.username.errors.append('User not activated')
            return False
        return True

news_website/forms/user.py
# -*- coding: utf-8 -*-
from flask_wtf import Form
from wtforms import TextField, PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from news_website.models.user import User


class RegisterForm(Form):
    username = TextField('Username', validators=[DataRequired(), Length(min=3, max=25)])
    first_name = TextField('first_name', validators=[DataRequired(), Length(min=3, max=25)])
    last_name = TextField('last_name', validators=[DataRequired(), Length(min=3, max=25)])
    email = TextField('Email', validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password', [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered")
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        return True

class EmailForm(Form):
    email = StringField('Email', validators=[DataRequired(), Email()])


class PasswordForm(Form):
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Confirm Password',
                              validators=[DataRequired(), EqualTo('password', message='Passwords must match')])


class UsernameForm(Form):
    username = StringField('Username', validators=[DataRequired()])
    username2 = StringField('Confirm Username',
                            validators=[DataRequired(), EqualTo('username', message='Usernames must match')])

news_website/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""
from flask import Flask, render_template
import os

from news_website.settings import ProdConfig
from news_website.assets import assets
from news_website.extensions import (
    bcrypt,
    cache,
    db,
    login_manager,
    mail,
    migrate,
    debug_toolbar,
    mongo
)
from news_website.views import public, user, news


def create_app(config_object=ProdConfig):
    """An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__)
    app.config.from_object(config_object)

    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def create_mongo_app(config_object=ProdConfig):
    """
    For differing from db(MySQL), create another app for PyMongo
    Args:
        config_object: config object, (DevConfig, ProdConfig)

    Returns: app

    """
    app = Flask("mongo_" + __name__)
    app.config.from_object(config_object)

    register_mongo_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_mongo_extensions(app):
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    mongo.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, mongo)
    mail.init_app(app)
    return None


def register_extensions(app):
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    mail.init_app(app)
    return None


def register_blueprints(app):
    app.register_blueprint(public.blueprint)
    app.register_blueprint(user.blueprint)
    app.register_blueprint(news.blueprint)
    return None


def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

news_website/services/__init__.py
__author__ = 'willmcginnis'

news_website/views/__init__.py
__author__ = 'willmcginnis'

news_website/views/admin.py
# -*- coding: utf-8 -*-
"""Public section, including homepage and signup."""
from flask import Blueprint, request

from flask_login import login_required, current_user
from news_website.utils import flash_errors, render_extensions
from news_website.models.news import News

blueprint = Blueprint('admin', __name__, static_folder="../static")


@blueprint.route("/new_blog", methods=["GET", "POST"])
@login_required
def new_blog():
    if not current_user.is_admin:
        return render_extensions('401.html')

    if request.method == 'POST':
        try:
            content = str(request.form['content'])
        except Exception:
            content = ''

        try:
            slug = str(request.form['slug'])
        except Exception:
            slug = ''

        try:
            title = str(request.form['title'])
        except Exception:
            title = ''

        news = News(title=title, body=content, slug=slug)
        news.save()

        current_user.posts.append(news)
        current_user.save()

    return render_extensions('admin/new_blog.html')

@blueprint.route("/edit_blog/<blog_id>/", methods=["GET", "POST"])
@login_required
def edit_blog(blog_id):
    if not current_user.is_admin:
        return render_extensions('401.html')

    if request.method == 'POST':
        try:
            content = str(request.form['content'])
        except Exception:
            content = ''

        try:
            slug = str(request.form['slug'])
        except Exception:
            slug = ''

        try:
            title = str(request.form['title'])
        except Exception:
            title = ''

        news = News(title=title, body=content, slug=slug)
        news.save()

        current_user.posts.append(news)
        current_user.save()

    post_obj = News.query.filter_by(id=int(blog_id)).first()
    post_content = {
        'title': str(post_obj.title),
        'slug': str(post_obj.slug),
        'body': str(post_obj.body),
    }

    return render_extensions('admin/edit_blog.html', post=post_content)

news_website/views/news.py
# -*- coding: utf-8 -*-
"""Public section, including homepage and signup.
 operation/ files shouldn't be related to web front
"""

from flask import Blueprint

from news_website.operations.op_news import (
    get_page,
    get_news_detail,
    get_newses_of_topic,
    get_hot_topics,
    get_number_of_newses
)
from news_website.utils import render_extensions

blueprint = Blueprint('news', __name__, static_folder="../static")


@blueprint.route("/news/<page>/", methods=["GET"])
def news_page(page=None):
    """

    :param page:
    :return:
    """

    page = int(page)
    _page_size = 3  # TODO: move into settings

    if page is None or page <= 0:
        next_page = 0
        prev_page = 1
        current = True
    else:
        next_page = page - 1
        prev_page = page + 1
        current = False

    newses = get_page(_page_size, page)
    hot_topics = get_hot_topics(5)
    return render_extensions("news/news_page.html",
                             newses=newses,
                             next_page=next_page,
                             prev_page=prev_page,
                             hot_topics=hot_topics,
                             current=current)


@blueprint.route("/news_detail/<pk>/", methods=["GET"])
def news_detail(pk):
    """

    :param pk:
    :return:
    """
    news_index = int(pk)
    news = get_news_detail(news_index)
    hot_topics = get_hot_topics(5)
    max_index = 1 if news_index == get_number_of_newses() else 0
    return render_extensions("news/news_detail.html",
                             news=news,
                             hot_topics=hot_topics,
                             max_index=max_index)

@blueprint.route("/topic/<topic>/<page>", methods=['GET'])
def topic_page(topic, page=None):
    page = int(page)
    _page_size = 3  # TODO: move into settings

    if page is None or page <= 0:
        next_page = 0
        prev_page = 1
        current = True
    else:
        next_page = page - 1
        prev_page = page + 1
        current = False
    newses = get_newses_of_topic(topic, _page_size, page)
    hot_topics = get_hot_topics(5)
    return render_extensions("news/topic_page.html",
                             newses=newses,
                             specified_topic=topic,
                             next_page=next_page,
                             prev_page=prev_page,
                             hot_topics=hot_topics,
                             current=current)

news_website/views/public.py
# -*- coding: utf-8 -*-
"""Public section, including homepage and signup."""
from flask import (Blueprint, request, render_template, flash, url_for, send_from_directory, make_response,
                   redirect, current_app)
import datetime

from flask_login import login_user, login_required, logout_user

from news_website.extensions import login_manager
from news_website.models.user import User
from news_website.forms.public import LoginForm
from news_website.forms.user import RegisterForm
from news_website.utils import flash_errors, render_extensions
from news_website.database import db

blueprint = Blueprint('public', __name__, static_folder="../static")


@login_manager.user_loader
def load_user(id):
    return User.get_by_id(int(id))


@blueprint.route("/", methods=["GET"])
def home():
    return render_template("public/home.html",
                             today=datetime.datetime.today().strftime("%Y-%m-%d at %H:%M:%S"))

@blueprint.route("/qin_collapse/")
def show_qin_collapse():
    print("Hey, boy ")
    return render_template("public/qin_collapse.html")


@blueprint.route("/login/", methods=["GET", "POST"])
def login():
    form = LoginForm(request.form)
    # Handle logging in
    if request.method == 'POST':
        if form.validate_on_submit():
            login_user(form.user)
            flash("You are logged in.", 'success')
            redirect_url = request.args.get("next") or url_for("user.profile")
            return redirect(redirect_url)
        else:
            flash_errors(form)
    return render_extensions("public/login.html", form=form)


@blueprint.route('/logout/')
@login_required
def logout():
    logout_user()
    flash('You are logged out.', 'info')
    return redirect(url_for('public.home'))


@blueprint.route("/register/", methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form, csrf_enabled=False)
    if form.validate_on_submit():
        new_user = User.create(username=form.username.data,
                               first_name=form.first_name.data,
                               last_name=form.last_name.data,
                               email=form.email.data,
                               password=form.password.data,
                               active=True)
        db.session.add(new_user)
        db.session.commit()
        flash("Thank you for registering. You can now log in.", 'success')
        return redirect(url_for('public.home'))
    else:
        flash_errors(form)
    return render_extensions('public/register.html', form=form)


@blueprint.route("/about/")
def about():
    form = LoginForm(request.form)
    return render_extensions("public/about.html", form=form)


@blueprint.route('/robots.txt')
@blueprint.route('/favicon.ico')
def static_from_root():
    return send_from_directory(current_app.static_folder, request.path[1:])


@blueprint.route('/sitemap.xml', methods=['GET'])
def sitemap():
    """
    Generate sitemap.xml. Makes a list of urls and date modified.
    """
    pages = []
    ten_days_ago = datetime.datetime.now() - datetime.timedelta(days=10)
    ten_days_ago = ten_days_ago.date().isoformat()
    # static pages
    for rule in current_app.url_map.iter_rules():
        if "GET" in rule.methods and len(rule.arguments) == 0:
            pages.append([rule.rule, ten_days_ago])

    sitemap_xml = render_template('public/sitemap_template.xml', pages=pages)
    response = make_response(sitemap_xml)
    response.headers["Content-Type"] = "application/xml"

    return response

news_website/views/user.py
# -*- coding: utf-8 -*-
from flask import (Blueprint, request, render_template, flash, url_for, send_from_directory, make_response,
                   redirect, current_app)

from flask_login import login_required, logout_user, current_user
from news_website.utils import flash_errors, render_extensions
from news_website.forms.user import PasswordForm, EmailForm, UsernameForm
from news_website.extensions import mail
from news_website.models.user import User
from flask_mail import Message
from itsdangerous import URLSafeTimedSerializer


blueprint = Blueprint("user", __name__, url_prefix='/users',
                      static_folder="../static")


@blueprint.route("/")
@login_required
def profile():
    return render_extensions("users/profile.html")


@blueprint.route('/reset', methods=["GET", "POST"])
def reset():
    form = EmailForm()
    if form.validate_on_submit():
        emailuser = User.query.filter_by(email=form.email.data).first_or_404()

        subject = "Password reset requested"
        from news_website.settings import Config

        ts = URLSafeTimedSerializer(Config.SECRET_KEY)
        token = ts.dumps(emailuser.email, salt='recover-key')

        recover_url = url_for('user.reset_with_token', token=token, _external=True)
        html = render_template('email/recover.html', recover_url=recover_url)

        msg = Message(html=html, recipients=[emailuser.email], subject=subject)
        mail.send(msg)

        return redirect(url_for('public.home'))
    else:
        flash_errors(form)

    return render_extensions('users/reset.html', resetform=form)


@blueprint.route('/reset/<token>', methods=["GET", "POST"])
def reset_with_token(token):
    try:
        from news_website.settings import Config

        ts = URLSafeTimedSerializer(Config.SECRET_KEY)
        email = ts.loads(token, salt="recover-key", max_age=86400)
    except:
        return render_template("404.html")

    form = PasswordForm()

    if form.validate_on_submit():
        emailuser = User.query.filter_by(email=email).first_or_404()
        emailuser.set_password(form.password.data)
        emailuser.save()
        return redirect(url_for('public.home'))
    else:
        flash_errors(form)

    return render_extensions('users/reset_with_token.html', resetform=form, token=token)


@blueprint.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = PasswordForm()
    if form.validate_on_submit():
        current_user.set_password(form.password.data)
        current_user.save()
        return redirect(url_for('user.profile'))
    else:
        flash_errors(form)

    return render_extensions('users/change_password.html', resetform=form)


@blueprint.route('/change_username', methods=['GET', 'POST'])
@login_required
def change_username():
    form = UsernameForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.save()
        return redirect(url_for('user.profile'))
    else:
        flash_errors(form)

    return render_extensions('users/change_username.html', resetform=form)


@blueprint.route('/unsubscribe')
@login_required
def unsubscribe():
    return render_extensions('users/unsubscribe.html')


@blueprint.route('/unsubscribe_confirm')
@login_required
def unsubscribe_confirm():
    user = current_user
    user.username = '%s (Unsubscribed)' % (user.username,)
    user.email = '%s (Unsubscribed)' % (user.email,)
    user.is_admin = False
    user.active = False
    user.save()
    logout_user()
    return redirect(url_for('public.home'))

news_website/views/word_count.py
from news_website.extensions import login_manager
from flask_login import login_user
from flask import Blueprint

blueprint = Blueprint('news', __name__, static_folder="../static")


@blueprint.route('/stat/', methods=['GET'])
def count_word():
    pass

news_website/templates/news/news_detail.html
{% extends "layout.html" %}

{% block page_title %}{{ news.title }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <h1>{{ news.title }}</h1>

                <p class="lead">
                    Reported at {{ news.report_time }}</a>
                </p>
                <hr>
                <p>Topics: {% for t in news.topics %} <a href="{{url_for('news.topic_page', topic=t.topic, page=0)}}">{{ t.topic }}{% endfor %}</a></p>
                <hr>
                {% for sentence in news.content.split("\n") %}
                <p>{{ sentence }}</p>
                {% endfor %}
                <hr>
                <ul class="pager">
                <li class="previous">
                    <a href="{{ url_for('news.news_detail', pk=news.id-1) }}">&larr; Last</a>
                </li>
                {% if not max_index %}
                    <li class="next">
                        <a href="{{ url_for('news.news_detail', pk=news.id+1) }}">Next &rarr;</a>
                    </li>
                {% endif %}
                </ul>
            </div>
            <div class="col-md-4">
                <br><br>

                <div class="well">
                    <h4>About</h4>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci
                        accusamus
                        laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>
                <div class="well">
                    <h4>Hot Topics</h4>

                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                {% for hot_t in hot_topics %}
                                <li><a href="{{ url_for('news.topic_page', topic=hot_t[0], page=0) }}">{{ hot_t[0] }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr>
    </div>
{% endblock %}

news_website/templates/news/news_page.html
{% extends "layout.html" %}

{% block page_title %}News{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1 class="page-header">
                    News
                </h1>
                {% for news in newses %}
                    <h2>
                        <a href="{{ url_for('news.news_detail', pk=news.id) }}">{{ news.title }}</a>
                    </h2>
                    <p class="lead">
                        Sumary: {{ news.abstract }}</a>
                    </p>
                    <p>Reported at: {{ news.report_time }}</p>
                    <hr>
                    <a class="btn btn-primary" href="{{ url_for('news.news_detail', pk=news.id) }}">Read More</a>
                    <hr>
                {% endfor %}
                <ul class="pager">
                    <li class="previous">
                        <a href="{{ url_for('news.news_page', page=prev_page) }}">&larr; Older</a>
                    </li>
                    {% if not current %}
                        <li class="next">
                            <a href="{{ url_for('news.news_page', page=next_page) }}">Newer &rarr;</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-md-4">
                <br><br>
                <div class="well">
                    <h4>Popular topics</h4>

                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                {% for hot_t in hot_topics %}
                                <li><a href="{{ url_for('news.topic_page', topic=hot_t[0], page=0) }}">{{ hot_t[0] }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr>
    </div>
{% endblock %}

news_website/templates/news/topic_page.html
{% extends "layout.html" %}

{% block page_title %}News{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1 class="page-header">
                    News
                </h1>
                {% for news in newses %}
                    <h2>
                        <a href="{{ url_for('news.news_detail', pk=news.id) }}">{{ news.title }}</a>
                    </h2>
                    <p class="lead">
                        Sumary: {{ news.abstract }}</a>
                    </p>
                    <p>Reported at: {{ news.report_time }}</p>
                    <hr>
                    <a class="btn btn-primary" href="{{ url_for('news.news_detail', pk=news.id) }}">Read More</a>
                    <hr>
                {% endfor %}
                <ul class="pager">
                    <li class="previous">
                        <a href="{{ url_for('news.topic_page', topic=specified_topic, page=prev_page) }}">&larr; Older</a>
                    </li>
                    {% if not current %}
                        <li class="next">
                            <a href="{{ url_for('news.topic_page', topic=specified_topic, page=next_page) }}">Newer &rarr;</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-md-4">
                <br><br>
                <div class="well">
                    <h4>Popular topics</h4>

                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                {% for hot_t in hot_topics %}
                                <li><a href="{{ url_for('news.topic_page', topic=hot_t[0], page=0) }}">{{ hot_t[0] }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr>
    </div>
{% endblock %}